routes/web.php
<?php

Route::middleware(['auth', 'Admin'])->group(function () {

    Route::get('/', 'HomeController@index');

    Route::resource('category', 'CategoryController');

    Route::resource('client', 'ClientController');

    Route::resource('contract', 'ContractController');

    Route::resource('sale', 'SalesController');

    Route::get('transaction/{id}','ContractController@transaction')->name('transaction');

    Route::post('addmoney','ContractController@addmoney')->name('addmoney');

    Route::resource('expenses', 'ExpensesController');

    Route::resource('tcategory', 'TcategoryController');

    Route::get('showexpenses', 'DetailsController@showexpenses')->name('showexpenses');
    Route::get('showcontract', 'DetailsController@showcontract')->name('showcontract');

    Route::get('showcategoryDetails/{id}', 'DetailsController@showcategoryDetails')->name('showcategoryDetails');

    Route::get('showsalescategoryDetails/{id}', 'DetailsController@showsalescategoryDetails')->name('showsalescategoryDetails');

    Route::resource('employe', 'EmployeController');
    Route::resource('section', 'SectionController');
    Route::resource('wallet', 'WalletController');


});


Auth::routes(['register' => false]);

app/Contract.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contract extends Model
{
    protected $guarded = [];

    public function sale()
    {
        return $this->belongsTo(Sales::class);
    }


    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }




}

app/Http/Controllers/ContractController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Client;
use App\Contract;
use App\Sales;
use App\Transaction;
use Illuminate\Http\Request;
use DB;
class ContractController extends Controller
{

    public function index()
    {
        $contracts = Contract::all();

        return view('contract.index', compact('contracts'));
    }


    public function create()
    {
        $categories = Category::all();

        $clients = Client::all();

        $sales = Sales::all();


        return view('contract.create', compact('categories', 'clients', 'sales'));
    }


    public function store(Request $request)
    {


        $request->validate([

            'category_id' => 'required',
            'client_id'    => 'required',
            'personal_id'  => 'required',
            'total'        => 'required',
            'advance'      => 'required',
            'deadline'     => 'required',
            'body'         => 'required',

        ]);

        $input = $request->all();

        $input['own'] = $input['total'] -  $input['advance'];

        $file = $request->file('avatar');

        if($file){

             $fileName = $file->getClientOriginalExtension();

             $fileName = uniqid() . 'mokhtar_ali.' . $fileName;

             $file->move('images/', $fileName);

             $input['avatar'] = $fileName;

        }

        Contract::create($input);

        session()->flash('message', 'تمت اضافه العقد بنجاح ');

        return redirect('/contract');
    }


    public function show($id)
    {
        $contract = Contract::findOrFail($id);

        $transactions  = DB::table('transactions')
        ->select('*')
        ->join('contracts', 'contracts.client_id', '=', 'transactions.client_id')
        ->join('sales', 'sales.id', '=', 'transactions.sale_id')
        ->where('contracts.id', $id)
        ->get();


        return view('contract.show', compact('contract', 'transactions'));
    }

    public function edit($id)
    {
        $contract = Contract::findOrFail($id);

        $categories = Category::all();

        $clients = Client::all();

        $sales = Sales::all();

        return view('contract.edit', compact('contract','categories','clients','sales'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([
            'category_id' => 'required',
            'client_id'    => 'required',
            'personal_id'  => 'required',
            'total'        => 'required',
            'advance'      => 'required',
            'deadline'     => 'required',
            'body'         => 'required',
        ]);

        $input = $request->all();

        $input['own'] = $input['total'] -  $input['advance'];

        $file = $request->file('avatar');

        if($file){

             $fileName = $file->getClientOriginalExtension();

             $fileName = uniqid() . 'mokhtar_ali.' . $fileName;

             $file->move('images/', $fileName);

             $input['avatar'] = $fileName;

        }else {

            $input['avatar'] = 'default.png';

        }

        Contract::findOrFail($id)->update($input);

        session()->flash('message', 'تمت تعديل العقد بنجاح ');

        return redirect('/contract');

    }


    public function destroy($id)
    {
        Contract::findOrFail($id)->delete();

        session()->flash('message', 'Contract Deleted Sucessfully.');

        return redirect('/contract');
    }

    public function transaction ($id) {

      $sales = Sales::all();
      return view('contract.add', compact('id', 'sales'));

    }


    public function addmoney (Request $request) {

   $request->validate([

    'amount'      => 'required',
    'sale_id'    => 'required',
    'client_id'   => 'required'
   ]);

   $input = $request->all();


      Transaction::create($input);


     $contract =  Contract::findOrFail($input['client_id'])->decrement('own', $input['amount']);

     session()->flash('message', 'تمت اضافه المبلغ  بنجاح ');

     return redirect('/contract');
    }
}

resources/views/contract/add.blade.php
@extends('layouts.admin')

@section('content')
            <div class="content-page">

                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box">
                            <div class="row align-items-center">
                                <div class="col-sm-6">
                                    <h4 class="page-title">اضافه عقد جديد</h4>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-right">
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الرئيسيه</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">العقود</a></li>
                                        <li class="breadcrumb-item active">اضافه عقد</li>
                                    </ol>
                                </div>
                            </div> <!-- end row -->
                        </div>

<form method="post" action="{{ route('addmoney') }}" enctype="multipart/form-data">
    @csrf

                        <div class="row">
                            <div class="col-12">
                                <div class="card m-b-30">
                                    <div class="card-body">
                                          <input type="hidden" value="{{ $id }}" name="client_id">
                                            <div class="form-group form-group-lg row">
                                                    <label for="example-text-input" class="col-sm-2 col-form-label">اسم الموظف</label>
                                                    <div class="col-sm-6">
                                                        <select class="form-control" name="sale_id" type="text">

                                                            @foreach ($sales as $sale)
                                                            <option value="{{ $sale->id }} "> {{$sale->name }} </option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                </div>

                                        <div class="form-group form-group-lg row">
                                                <label for="example-text-input" class="col-sm-2 col-form-label">  المبلغ</label>
                                                <div class="col-sm-6">
                                                    <input class="form-control" name="amount" type="number" placeholder="المبلغ المدفوع " id="example-text-input" required>
                                                </div>
                                            </div>



                                        <div class="row">
                                            <div class="col-sm-2">
                                            </div>
                                                <div class="col-sm-6 col-md-offset-3">
                                                    <input class="btn-block btn btn-primary" type="submit" value="اضف عميل جديد">
                                                </div>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

                @endsection

resources/views/contract/create.blade.php
@extends('layouts.admin')

@section('content')
            <div class="content-page">

                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box">
                            <div class="row align-items-center">
                                <div class="col-sm-6">
                                    <h4 class="page-title">اضافه عقد جديد</h4>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-right">
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الرئيسيه</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">العقود</a></li>
                                        <li class="breadcrumb-item active">اضافه عقد</li>
                                    </ol>
                                </div>
                            </div> <!-- end row -->
                        </div>

<form method="post" action="{{ route('contract.store') }}" enctype="multipart/form-data">
    @csrf

                        <div class="row">
                            <div class="col-12">
                                <div class="card m-b-30">
                                    <div class="card-body">
                                        <div class="form-group form-group-lg row">
                                            <label for="example-text-input" class="col-sm-2 col-form-label">نوع الخدمه </label>
                                            <div class="col-sm-6">
                                                <select class="form-control" name="category_id" type="text">

                                                    @foreach ($categories as $category)
                                                    <option value="{{ $category->id }} "> {{$category->name }} </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group form-group-lg row">
                                                <label for="example-text-input" class="col-sm-2 col-form-label">اسم العميل</label>
                                                <div class="col-sm-6">
                                                    <select class="form-control" name="client_id" type="text">

                                                        @foreach ($clients as $client)
                                                        <option value="{{ $client->id }} "> {{$client->name }} </option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="form-group form-group-lg row">
                                                    <label for="example-text-input" class="col-sm-2 col-form-label">اسم الموظف</label>
                                                    <div class="col-sm-6">
                                                        <select class="form-control" name="sale_id" type="text">

                                                            @foreach ($sales as $sale)
                                                            <option value="{{ $sale->id }} "> {{$sale->name }} </option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                </div>

                                        <div class="form-group form-group-lg row">
                                                <label for="example-text-input" class="col-sm-2 col-form-label"> رقم الهويه</label>
                                                <div class="col-sm-6">
                                                    <input class="form-control" name="personal_id" type="text" placeholder=" رقم الهويه " id="example-text-input" required>
                                                </div>
                                            </div>

                                            <div class="form-group form-group-lg row">
                                                    <label for="example-text-input" class="col-sm-2 col-form-label">  قيمه العقد</label>
                                                    <div class="col-sm-6">
                                                        <input class="form-control" name="total" type="text" placeholder=" القيمه الاجماليه للعقد " id="example-text-input" required>
                                                    </div>
                                                </div>
                                                <div class="form-group form-group-lg row">
                                                        <label for="example-text-input" class="col-sm-2 col-form-label"> قيمه المقدم</label>
                                                        <div class="col-sm-6">
                                                            <input class="form-control" name="advance" type="text" placeholder="المبلغ المدفوع " id="example-text-input" required>
                                                        </div>
                                                    </div>
                                                    <div class="form-group form-group-lg row">
                                                            <label for="example-text-input" class="col-sm-2 col-form-label"> ميعاد التسليم</label>
                                                            <div class="col-sm-6">
                                                                <input class="form-control" name="deadline" type="date" placeholder=" ميعاد تسليم العميل " id="example-text-input" required>
                                                            </div>
                                                        </div>

                                                        <div class="form-group form-group-lg row">
                                                                <label for="example-text-input" class="col-sm-2 col-form-label"> اسم الدومين</label>
                                                                <div class="col-sm-6">
                                                                    <input class="form-control" name="domain" type="text" placeholder="اسم الدومين في حاله الويب " id="example-text-input">
                                                                </div>
                                                            </div>
                                                            <div class="form-group form-group-lg row">
                                                                    <label for="example-text-input" class="col-sm-2 col-form-label"> صوره من العقد</label>
                                                                    <div class="col-sm-6">
                                                                        <input type="file" class="form-control" name="avatar" type="text" required >
                                                                    </div>
                                                                </div>

                                                                <div class="form-group form-group-lg row">
                                                                        <label for="example-text-input" class="col-sm-2 col-form-label"> ملاحظات</label>
                                                                        <div class="col-sm-6">
                                                                            <textarea class="form-control" name="body" type="text" placeholder="ملاحظات" id="example-text-input"></textarea>
                                                                        </div>
                                                                    </div>

                                        <div class="row">
                                            <div class="col-sm-2">
                                            </div>
                                                <div class="col-sm-6 col-md-offset-3">
                                                    <input class="btn-block btn btn-primary" type="submit" value="اضف عميل جديد">
                                                </div>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

                @endsection

resources/views/contract/edit.blade.php
@extends('layouts.admin')

@section('content')
            <div class="content-page">

                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box">
                            <div class="row align-items-center">
                                <div class="col-sm-6">
                                    <h4 class="page-title">تعديل عقد </h4>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-right">
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الرئيسيه</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">العقود</a></li>
                                        <li class="breadcrumb-item active">تعديل عقد</li>
                                    </ol>
                                </div>
                            </div> <!-- end row -->
                        </div>

<form method="post" action="{{ route('contract.update', $contract->id) }}" enctype="multipart/form-data">
    @method('PUT')
    @csrf

                        <div class="row">
                            <div class="col-12">
                                <div class="card m-b-30">
                                    <div class="card-body">
                                        <div class="form-group form-group-lg row">
                                            <label for="example-text-input" class="col-sm-2 col-form-label">نوع الخدمه </label>
                                            <div class="col-sm-6">
                                                <select class="form-control" name="category_id" type="text">

                                                    @foreach ($categories as $category)
                                                    <option value="{{ $category->id }} "> {{$category->name }} </option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group form-group-lg row">
                                                <label for="example-text-input" class="col-sm-2 col-form-label">اسم العميل</label>
                                                <div class="col-sm-6">
                                                    <select class="form-control" name="client_id" type="text">

                                                        @foreach ($clients as $client)
                                                        <option value="{{ $client->id }} "> {{$client->name }} </option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="form-group form-group-lg row">
                                                    <label for="example-text-input" class="col-sm-2 col-form-label">اسم الموظف</label>
                                                    <div class="col-sm-6">
                                                        <select class="form-control" name="sale_id" type="text">

                                                            @foreach ($sales as $sale)
                                                            <option value="{{ $sale->id }} "> {{$sale->name }} </option>
                                                            @endforeach
                                                        </select>
                                                    </div>
                                                </div>

                                        <div class="form-group form-group-lg row">
                                                <label for="example-text-input" class="col-sm-2 col-form-label"> رقم الهويه</label>
                                                <div class="col-sm-6">
                                                    <input class="form-control" name="personal_id" type="text" id="example-text-input" required value="{{ $contract->personal_id }}">
                                                </div>
                                            </div>

                                            <div class="form-group form-group-lg row">
                                                    <label for="example-text-input" class="col-sm-2 col-form-label">  قيمه العقد</label>
                                                    <div class="col-sm-6">
                                                        <input class="form-control" name="total" type="text" id="example-text-input" required value="{{ $contract->total }}">
                                                    </div>
                                                </div>
                                                <div class="form-group form-group-lg row">
                                                        <label for="example-text-input" class="col-sm-2 col-form-label"> قيمه المقدم</label>
                                                        <div class="col-sm-6">
                                                            <input class="form-control" name="advance" type="text" id="example-text-input" required value="{{ $contract->advance }}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group form-group-lg row">
                                                            <label for="example-text-input" class="col-sm-2 col-form-label"> ميعاد التسليم</label>
                                                            <div class="col-sm-6">
                                                                <input class="form-control" name="deadline" type="date" id="example-text-input" required value="{{ $contract->deadline }}">
                                                            </div>
                                                        </div>

                                                        <div class="form-group form-group-lg row">
                                                                <label for="example-text-input" class="col-sm-2 col-form-label"> اسم الدومين</label>
                                                                <div class="col-sm-6">
                                                                    <input class="form-control" name="domain" type="text" id="example-text-input" value="{{ $contract->domain }}">
                                                                </div>
                                                            </div>
                                                            <div class="form-group form-group-lg row">
                                                                    <label for="example-text-input" class="col-sm-2 col-form-label"> صوره من العقد</label>
                                                                    <div class="col-sm-6">
                                                                        <input type="file" class="form-control" name="avatar" type="text" >
                                                                    </div>
                                                                </div>

                                                                <div class="form-group form-group-lg row">
                                                                        <label for="example-text-input" class="col-sm-2 col-form-label"> ملاحظات</label>
                                                                        <div class="col-sm-6">
                                                                            <textarea class="form-control" name="body" type="text" placeholder="ملاحظات" id="example-text-input"></textarea>
                                                                        </div>
                                                                    </div>

                                        <div class="row">
                                            <div class="col-sm-2">
                                            </div>
                                                <div class="col-sm-6 col-md-offset-3">
                                                    <input class="btn-block btn btn-primary" type="submit" value="تعديل عميل ">
                                                </div>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

                @endsection

resources/views/contract/index.blade.php
@extends('layouts.admin')

@section('content')

        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-sm-6">
                                <h4 class="page-title">العقود</h4>
                            </div>
                            <div class="col-sm-6">
                            </div>
                        </div>
                        <!-- end row -->
                    </div>
                    <!-- end page-title -->


                    <div class="row m-t-30">
                            @foreach($contracts as $contract )

                        <div class="col-xl-3 col-md-6">
                            <div class="card pricing-box mt-4">
                                <div class="pricing-icon">
                                    <i class="ti-shield bg-success"></i>
                                    <a style="float:left" href="{{ route('contract.edit', $contract->id) }}" class="btn btn-success waves-effect waves-light">تعديل</a>
                                                          
                                    <form style="display: contents;" method="post" action="{{ route('contract.destroy', $contract->id) }}">

                                            @method('DELETE')
                                            @csrf
                                            <button class="delete-btn btn btn-danger waves-effect waves-light">مسح</button>
                                    </form>
                                </div>
                                <div class="pricing-content">
                                    <div class="text-center">
                                        <h5 class="text-uppercase mt-5">{{ $contract->client->name }}</h5>
                                        <div class="pricing-plan mt-4 pt-2">
                                            <h1>{{ $contract->id }} </h1>
                                            <h4>{{ $contract->category->name  }} </h4>
                                        </div>
                                        <div class="pricing-border mt-5"></div>
                                    </div>
                                    <div class="pricing-features mt-4">
                                        <p class="font-14 mb-2">   ميعاد التسليم <i class="ti-check-box text-success mr-3"></i> {{ $contract->deadline }} </p>
                                        <p class="font-14 mb-2">   الاجمالي <i class="ti-check-box text-success mr-3"></i> {{ $contract->total }} </p>
                                        <p class="font-14 mb-2"> المتبقي  <i class="ti-check-box text-danger mr-3"></i> {{ $contract->own }} </p>
                                    </div>
                                    <div class="pricing-border mt-4"></div>
                                    <div class="mt-4 pt-3 text-center">
                                        <a href="{{ route('contract.show', $contract->id) }}" class="btn btn-success btn-lg w-100 btn-round">عرض العقد</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                @endforeach

                    </div>

                </div>
                <!-- container-fluid -->

            </div>










@endsection