routes/web.php
<?php

Route::middleware(['auth', 'Admin'])->group(function () {

    Route::get('/', 'HomeController@index');

    Route::resource('category', 'CategoryController');

    Route::resource('client', 'ClientController');

    Route::resource('contract', 'ContractController');

    Route::resource('sale', 'SalesController');

    Route::get('transaction/{id}','ContractController@transaction')->name('transaction');

    Route::post('addmoney','ContractController@addmoney')->name('addmoney');

    Route::resource('expenses', 'ExpensesController');

    Route::resource('tcategory', 'TcategoryController');

    Route::get('showexpenses', 'DetailsController@showexpenses')->name('showexpenses');
    Route::get('showcontract', 'DetailsController@showcontract')->name('showcontract');

    Route::get('showcategoryDetails/{id}', 'DetailsController@showcategoryDetails')->name('showcategoryDetails');

    Route::get('showsalescategoryDetails/{id}', 'DetailsController@showsalescategoryDetails')->name('showsalescategoryDetails');

    Route::resource('employe', 'EmployeController');
    Route::resource('section', 'SectionController');
    Route::resource('wallet', 'WalletController');


});


Auth::routes(['register' => false]);

app/Sales.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sales extends Model
{
    protected $guarded = [];

    public function contract()
    {
        return $this->hasMany(Contract::class);
    }
}

app/Http/Controllers/SalesController.php
<?php

namespace App\Http\Controllers;

use App\Sales;
use Illuminate\Http\Request;

class SalesController extends Controller
{
    public function index()
    {
        $sales = Sales::all();

        return view('sales.index', compact('sales'));

    }


    public function create()
    {
        return view('sales.create');
    }


    public function store(Request $request)
    {
        $request->validate([

            'name' => 'required | min:3'
        ]);

        $input = $request->all();

        Sales::create($input);

        session()->flash('message', 'تمت اضافه الموظف بنجاح ');

        return redirect('/sale');

    }


    public function edit($id)
    {
        $sale = Sales::findOrFail($id);

        return view('sales.edit', compact('sale'));
    }


    public function update(Request $request, $id)
    {
        $request->validate([

            'name' => 'required | min:3'
        ]);

        $input = $request->all();

        Sales::findOrFail($id)->update($input);

        session()->flash('message', 'تمت تعديل الخدمه بنجاح ');

        return redirect('/sale');

    }


    public function destroy($id)
    {
        Sales::findOrFail($id)->delete();

        return redirect('/sale');
    }
}

resources/views/sales/create.blade.php
@extends('layouts.admin')

@section('content')
            <div class="content-page">

                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box">
                            <div class="row align-items-center">
                                <div class="col-sm-6">
                                    <h4 class="page-title">اضافه خدمه جديد</h4>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-right">
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الرئيسيه</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الخدمات</a></li>
                                        <li class="breadcrumb-item active">اضافه صنف</li>
                                    </ol>
                                </div>
                            </div> <!-- end row -->
                        </div>

<form method="post" action="{{ route('sale.store') }}">
    @csrf

                        <div class="row">
                            <div class="col-12">
                                <div class="card m-b-30">
                                    <div class="card-body">
                                        <div class="form-group form-group-lg row">
                                            <label for="example-text-input" class="col-sm-2 col-form-label">اسم الموظف</label>
                                            <div class="col-sm-6">
                                                <input class="form-control" name="name" type="text" placeholder="ادخل اسم الموظف" id="example-text-input">
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-sm-2">
                                            </div>
                                                <div class="col-sm-6 col-md-offset-3">
                                                    <input class="btn-block btn btn-primary" type="submit" value="اضف الموظف ">
                                                </div>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

                @endsection

resources/views/sales/index.blade.php
@extends('layouts.admin')

@section('content')




            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box">
                            <div class="row align-items-center">
                                <div class="col-sm-6">
                                    <h4 class="page-title">Data Table</h4>
                                </div>
                                <div class="col-sm-6">

                                </div>
                            </div> <!-- end row -->
                        </div>
                        <!-- end page-title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="card m-b-30">
                                    <div class="card-body">


                                        <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                            <thead>
                                            <tr>
                                                <th>اسم الموظف</th>
                                                <th>التحكم</th>
                                            </tr>
                                            </thead>


                                            <tbody>

                                                @foreach($sales as $sale )
                                            <tr>
                                                <td>{{ $sale->name }}</td>
                                                <td>
                                                        <div class="button-items">

                                                                <a href="{{ route('sale.edit', $sale->id ) }}" class="btn btn-success waves-effect waves-light">تعديل</a>

                                                                <form style="display: contents;" method="post" action="{{ route('sale.destroy', $sale->id ) }}">

                                                                        @method('DELETE')
                                                                        @csrf
                                                                        <a type="button" class="delete-btn btn btn-danger waves-effect waves-light">مسح</a>

                                                                        </form>
                                                            </div>
                                                </td>
                                            </tr>
                                            @endforeach
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->




                    </div>
                    <!-- container-fluid -->

                </div>
                <!-- content -->



@endsection