routes/web.php
<?php

Route::middleware(['auth', 'Admin'])->group(function () {

    Route::get('/', 'HomeController@index');

    Route::resource('category', 'CategoryController');

    Route::resource('client', 'ClientController');

    Route::resource('contract', 'ContractController');

    Route::resource('sale', 'SalesController');

    Route::get('transaction/{id}','ContractController@transaction')->name('transaction');

    Route::post('addmoney','ContractController@addmoney')->name('addmoney');

    Route::resource('expenses', 'ExpensesController');

    Route::resource('tcategory', 'TcategoryController');

    Route::get('showexpenses', 'DetailsController@showexpenses')->name('showexpenses');
    Route::get('showcontract', 'DetailsController@showcontract')->name('showcontract');

    Route::get('showcategoryDetails/{id}', 'DetailsController@showcategoryDetails')->name('showcategoryDetails');

    Route::get('showsalescategoryDetails/{id}', 'DetailsController@showsalescategoryDetails')->name('showsalescategoryDetails');

    Route::resource('employe', 'EmployeController');
    Route::resource('section', 'SectionController');
    Route::resource('wallet', 'WalletController');


});


Auth::routes(['register' => false]);

app/Wallet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wallet extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/WalletController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Wallet;
use App\WalletTotal;
class WalletController extends Controller
{

    public function index()
    {
        $wallets = Wallet::all();

        return view('wallet.index', compact('wallets'));
    }

    public function create()
    {
        return view('wallet.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'from' => 'required',
            'amount' => 'required | numeric',
        ]);

        $input = $request->all();

        Wallet::create($input);

        $total  =  Wallet::sum('amount');

        WalletTotal::findOrFail('1')->update([
            'amount' => $total
        ]);

        session()->flash('message', 'تمت  الاضافه بنجاح ');

        return redirect('/wallet');
    }


    public function edit($id)
    {

      $wallet =   Wallet::findOrFail($id);

      return view('wallet.edit', compact('wallet'));    
    
    }

    public function update(Request $request, $id)
    {
        $wallet =   Wallet::findOrFail($id);

        $request->validate([
            'from' => 'required',
            'amount' => 'required | numeric',
        ]);

        $input = $request->all();

        $total  =  Wallet::sum('amount');

        WalletTotal::findOrFail('1')->update([
            'amount' => $total
        ]);
        
        $wallet->update($input);

        session()->flash('message', 'تمت  التعديل بنجاح ');

        return redirect('/wallet');
    }
    

    public function destroy($id)
    {
        Wallet::findOrFail($id)->delete();

        
        session()->flash('message', 'تمت  الحذف بنجاح ');

        return redirect('/wallet');

    }
}

resources/views/wallet/create.blade.php
@extends('layouts.admin')

@section('content')
            <div class="content-page">

                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box">
                            <div class="row align-items-center">
                                <div class="col-sm-6">
                                    <h4 class="page-title">اضافه قسم جديد</h4>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-right">
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الرئيسيه</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الاقسام</a></li>
                                        <li class="breadcrumb-item active">اضافه قسم</li>
                                    </ol>
                                </div>
                            </div> <!-- end row -->
                        </div>

<form method="post" action="{{ route('wallet.store') }}">
    @csrf

                        <div class="row">
                            <div class="col-12">
                                <div class="card m-b-30">
                                    <div class="card-body">
                                        <div class="form-group form-group-lg row">
                                            <label for="example-text-input" class="col-sm-2 col-form-label">المدين </label>
                                            <div class="col-sm-6">
                                                <select class="form-control" name="from" id="example-text-input">
                                                    <option value="المكتب">المكتب</option>
                                                    <option value="تحويل">تحويل</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group form-group-lg row">
                                                <label for="example-text-input" class="col-sm-2 col-form-label">المبلغ </label>
                                                <div class="col-sm-6">
                                                    <input class="form-control" name="amount" type="number" placeholder="ادخل المبلغ " id="example-text-input">
                                                </div>
                                            </div>


                                        <div class="row">
                                            <div class="col-sm-2">
                                            </div>
                                                <div class="col-sm-6 col-md-offset-3">
                                                    <input class="btn-block btn btn-primary" type="submit" value="اضف المبلغ ">
                                                </div>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

                @endsection

resources/views/wallet/edit.blade.php
@extends('layouts.admin')

@section('content')
            <div class="content-page">

                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box">
                            <div class="row align-items-center">
                                <div class="col-sm-6">
                                    <h4 class="page-title">اضافه قسم جديد</h4>
                                </div>
                                <div class="col-sm-6">
                                    <ol class="breadcrumb float-right">
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الرئيسيه</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:void(0);">الاقسام</a></li>
                                        <li class="breadcrumb-item active">اضافه قسم</li>
                                    </ol>
                                </div>
                            </div> <!-- end row -->
                        </div>

<form method="post" action="{{ route('wallet.update', $wallet->id) }}">
    @method('PUT')
    @csrf

                        <div class="row">
                            <div class="col-12">
                                <div class="card m-b-30">
                                    <div class="card-body">
                                        <div class="form-group form-group-lg row">
                                            <label for="example-text-input" class="col-sm-2 col-form-label">المدين </label>
                                            <div class="col-sm-6">
                                                <select class="form-control" name="from" id="example-text-input">
                                                    <option value="المكتب"  @if($wallet->from == 'المكتب') 'selected' @endif>المكتب</option>
                                                    <option value="تحويل" @if($wallet->from == 'تحويل') 'selected' @endif>تحويل</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group form-group-lg row">
                                                <label for="example-text-input" class="col-sm-2 col-form-label">المبلغ </label>
                                                <div class="col-sm-6">
                                                <input class="form-control" name="amount" value="{{ $wallet->amount }}" type="number" placeholder="ادخل المبلغ " id="example-text-input">
                                                </div>
                                            </div>


                                        <div class="row">
                                            <div class="col-sm-2">
                                            </div>
                                                <div class="col-sm-6 col-md-offset-3">
                                                    <input class="btn-block btn btn-primary" type="submit" value="تعديل المبلغ ">
                                                </div>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>

                @endsection

resources/views/wallet/index.blade.php
@extends('layouts.admin')

@section('content')




            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container-fluid">
                        <div class="page-title-box">
                            <div class="row align-items-center">
                                <div class="col-sm-6">
                                    <h4 class="page-title"> بيانات الخزنه </h4>
                                </div>
                                <div class="col-sm-6">
                                </div>
                            </div> <!-- end row -->
                        </div>
                        <!-- end page-title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="card m-b-30">
                                    <div class="card-body">


                                        <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                            <thead>
                                            <tr>
                                                <th> المدين</th>
                                                <th> المبلغ</th>
                                                <th> التاريخ</th>
                                                <th>التحكم</th>
                                            </tr>
                                            </thead>


                                            <tbody>

                                                @foreach($wallets as $wallet )
                                            <tr>
                                                <td>{{ $wallet->from }}</td>
                                                <td>{{ $wallet->amount }}</td>
                                                <td>{{ date("Y M d", strtotime($wallet->created_at)) }}</td>
                                                <td>
                                                        <div class="button-items">

                                                                <a href="{{ route('wallet.edit', $wallet->id ) }}" class="btn btn-success waves-effect waves-light">تعديل</a>

                                                                <form style="display: contents;" method="post" action="{{ route('wallet.destroy', $wallet->id ) }}">

                                                                        @method('DELETE')
                                                                        @csrf
                                                                        <button class="delete-btn btn btn-danger waves-effect waves-light">مسح</button>

                                                                        </form>
                                                            </div>
                                                </td>
                                            </tr>
                                            @endforeach
                                            </tbody>
                                        </table>

                                    </div>
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->




                    </div>
                    <!-- container-fluid -->

                </div>
                <!-- content -->



@endsection